begin;

create table if not exists public.report_moderation_events (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  issue_id text,
  event_type text not null,
  decision text not null check (decision in ('allow', 'deny')),
  source text not null,
  category text,
  reason_code text,
  reason_message text,
  score double precision,
  created_at timestamptz not null default now()
);

create index if not exists idx_report_moderation_events_reporter
  on public.report_moderation_events(reporter_id, created_at desc);

create index if not exists idx_report_moderation_events_issue
  on public.report_moderation_events(issue_id);

alter table public.report_moderation_events enable row level security;

drop policy if exists "reporter can insert moderation events" on public.report_moderation_events;
create policy "reporter can insert moderation events"
on public.report_moderation_events
for insert
to authenticated
with check (reporter_id = auth.uid());

drop policy if exists "reporter can read own moderation events" on public.report_moderation_events;
create policy "reporter can read own moderation events"
on public.report_moderation_events
for select
to authenticated
using (reporter_id = auth.uid());

drop policy if exists "admins can read moderation events" on public.report_moderation_events;
create policy "admins can read moderation events"
on public.report_moderation_events
for select
to authenticated
using (
  exists (
    select 1
    from public.admins
    where admins.user_id = auth.uid()
  )
);

commit;